engines:
  eslint:
    enabled: true
ratings:
  paths:
  - "client/**"
  - "server/**"
  - "collections/**"
  - "lib/**"
  - "tests/**"
exclude_paths:
- "packages/**" #Paths that you want excluded from our analysis.
